@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "Developer")

System_Boundary(DFetch, "Dfetch") {

    Boundary(DFetchCommands, "Commands") {
        Component(compCommon, "Common", "python", "Does stuff")
        Component(compCommand, "Command", "python", "Does stuff")

        Component(compCheck, "Check", "python", "Checks for updates")
        Component(compDiff, "Diff", "python", "Creates patch of local changes")
        Component(compEnv, "Environment", "python", "Shows local tools")
        Component(compFormatPatch, "FormatPatch", "python", "Format patch for export")
        Component(compFreeze, "Freeze", "python", "Pins all projects")
        Component(compImport, "Import", "python", "Imports from VCS")
        Component(compInit, "Init", "python", "Initializes a manifest")
        Component(compReport, "Report", "python", "Reports status")
        Component(compUpdate, "Update", "python", "Updates all projects")
        Component(compUpdatePatch, "UpdatePatch", "python", "Updates patch")
        Component(compValidate, "Validate", "python", "Validates manifest")

        Rel_U(compCheck, compCommand, "Extends")
        Rel_U(compDiff, compCommand, "Extends")
        Rel_U(compEnv, compCommand, "Extends")
        Rel_U(compFormatPatch, compCommand, "Extends")
        Rel_U(compFreeze, compCommand, "Extends")
        Rel_U(compImport, compCommand, "Extends")
        Rel_U(compInit, compCommand, "Extends")
        Rel_U(compReport, compCommand, "Extends")
        Rel_U(compUpdate, compCommand, "Extends")
        Rel_U(compUpdatePatch, compCommand, "Extends")
        Rel_U(compValidate, compCommand, "Extends")

        Rel_U(compUpdate, compCommon, "Uses")
        Rel_U(compCheck, compCommon, "Uses")
    }

    Container(contManifest, "Manifest", "python", "Parsing, editing and finding of manifests.")
    Container(contProject, "Project", "python", "Main project that has a manifest.")
    Container(contVcs, "Vcs", "python", "Abstraction of various Version Control Systems.")
    Container(contReporting, "Reporting", "python", "Output formatters for various reporting formats.")

    Rel(compCheck, contManifest, "Uses")
    Rel(compCheck, contProject, "Uses")
    Rel(compCheck, contReporting, "Uses")

    Rel(compDiff, contManifest, "Uses")
    Rel(compDiff, contProject, "Uses")

    Rel(compEnv, contProject, "Uses")

    Rel(compFormatPatch, contManifest, "Uses")
    Rel(compFormatPatch, contProject, "Uses")
    Rel(compFormatPatch, contVcs, "Uses")

    Rel(compFreeze, contManifest, "Uses")
    Rel(compFreeze, contProject, "Uses")

    Rel(compImport, contManifest, "Uses")
    Rel(compImport, contProject, "Uses")
    Rel(compImport, contVcs, "Uses")

    Rel(compReport, contManifest, "Uses")
    Rel(compReport, contProject, "Uses")
    Rel(compReport, contReporting, "Uses")

    Rel(compUpdate, contManifest, "Uses")
    Rel(compUpdate, contProject, "Uses")

    Rel(compUpdatePatch, contManifest, "Uses")
    Rel(compUpdatePatch, contProject, "Uses")
    Rel(compUpdatePatch, contVcs, "Uses")

    Rel(compValidate, contManifest, "Uses")

    Rel(contProject, contReporting, "Uses")
    Rel_R(contProject, contManifest, "Has")
    Rel_U(contReporting, contManifest, "Uses")
    Rel(contProject, contVcs, "Uses")
}

Rel(user, compCommand, "Uses")

@enduml
