@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "Developer")

System_Boundary(DFetch, "Dfetch") {

    Container(contCommands, "Commands", "python", "Parsing, editing and finding of manifests.")

    Container(contManifest, "Manifest", "python", "Parsing, editing and finding of manifests.")
    Boundary(DfetchProject, "Project", "python", "Main project that has a manifest.") {

        Component(compAbstractCheckReporter, "AbstractCheckReporter", "python", "Abstract interface for generating a check report.")
        Component(compGitSub, "GitSubproject", "python", "A subproject based on git.")
        Component(compMetadata, "Metadata", "python", "A file containing metadata about a project.")
        Component(compSvnSub, "SvnSubproject", "python", "A subproject based on svn.")
        Component(compSubProject, "SubProject", "python", "An abstract subproject.")
        Component(compSuperProject, "SuperProject", "python", "An abstract superproject.")
        Component(compGitSuper, "GitSuperProject", "python", "A superproject based on git.")
        Component(compSvnSuper, "SvnSuperProject", "python", "A superproject based on svn.")
        Component(compNoVcsSuper, "NoVcsSuperProject", "python", "A superproject without VCS.")

        Rel_U(compGitSub, compSubProject, "Implements")
        Rel_U(compSvnSub, compSubProject, "Implements")
        Rel(compSubProject, compAbstractCheckReporter, "Uses")
        Rel_L(compSubProject, compMetadata, "Uses")

        Rel_U(compGitSuper, compSuperProject, "Implements")
        Rel_U(compSvnSuper, compSuperProject, "Implements")
        Rel_U(compNoVcsSuper, compSuperProject, "Implements")
    }

    Container(contVcs, "Vcs", "python", "Abstraction of various Version Control Systems.")
    Container(contReporting, "Reporting", "python", "Output formatters for various reporting formats.")

    Rel(contCommands, compSuperProject, "Uses")
    Rel(contCommands, compSubProject, "Uses")
    Rel(contReporting, compAbstractCheckReporter, "Implements")
    Rel_R(contReporting, compMetadata, "Uses")
    Rel_U(compMetadata, contManifest, "Has")
    Rel(compSuperProject, contManifest, "Has")
    Rel_U(contReporting, contManifest, "Uses")
    Rel(compGitSub, contVcs, "Uses")
    Rel(compSvnSub, contVcs, "Uses")
    Rel(compGitSuper, contVcs, "Uses")
    Rel(compSvnSuper, contVcs, "Uses")
}

Rel(user, contCommands, "Uses")

@enduml
