# This is a generated file by dfetch. Don't edit this, but edit the manifest.
# For more info see https://dfetch.rtfd.io/en/latest/getting_started.html
dfetch:
  branch: ''
  hash: 428a1aa8c0009c0c0583bbb49edd99b7
  last_fetch: 20/04/2026, 21:25:15
  patch: ''
  remote_url: https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip
  revision: sha256:9883fdd4a49d4fb66bd8177ba6625ef9a64aa45899767dde3d36aa425756b11e
  tag: ''
