# See https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod/Dockerfile

tasks:
  - init: pip install -e .

github:
  prebuilds:
    addBadge: true
    addCheck: true
    addComment: false
    branches: true
    master : true
    pullRequests : true
    pullRequestsFromForks : false

workspaceLocation: dfetch/dfetch.code-workspace
vscode:
  extensions:
    - lextudio.restructuredtext
    - alexkrechik.cucumberautocomplete
    - ms-python.python
    - mhutchie.git-graph
    - bungcip.better-toml
