# See https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod/Dockerfile

tasks:
  - init: pip install -e .[development,docs,casts]

workspaceLocation: dfetch/dfetch.code-workspace
vscode:
  extensions:
    - lextudio.restructuredtext
    - alexkrechik.cucumberautocomplete
    - ms-python.python
    - ms-python.isort
    - ms-python.black-formatter
    - mhutchie.git-graph
    - bungcip.better-toml
    - trond-snekvik.simple-rst
    - jebbs.plantuml
