from typing import Any, Optional, Union

class Halo:
    text: str
    spinner: str
    color: str
    interval: int
    stream: Any
    enabled: bool

    def __init__(
        self,
        text: Optional[str] = None,
        text_color: Optional[str] = None,
        color: Optional[str] = None,
        spinner: Optional[Union[str, dict]] = None,
        animation: Optional[str] = None,
        placement: Optional[str] = None,
        interval: Optional[int] = None,
        enabled: Optional[bool] = None,
        stream: Optional[Any] = None,
    ) -> None: ...
    def start(self) -> "Halo": ...
    def stop(self) -> None: ...
    def succeed(self, text: Optional[str] = None) -> None: ...
    def fail(self, text: Optional[str] = None) -> None: ...
    def warn(self, text: Optional[str] = None) -> None: ...
    def info(self, text: Optional[str] = None) -> None: ...
    def clear(self) -> None: ...
    def render(self) -> None: ...
    def persist(self) -> None: ...
    def __enter__(self) -> "Halo": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

def halo(
    text: str = "",
    spinner: Union[str, dict] = "dots",
    color: str = "cyan",
    interval: Optional[int] = None,
    stream: Optional[Any] = None,
    enabled: Optional[bool] = None,
) -> Halo: ...
