from typing import Any, Iterator, List, Optional, Union

class PatchSet:
    applied: bool
    items: List[Any]

    def __init__(self, patch_text: Optional[str] = None) -> None: ...
    
    def parse(self, patch_text: str) -> None: ...
    def apply(self, strip:int=0, root:Optional[str]=None, fuzz:bool=False) -> bool: ...
    def revert(self) -> None: ...
    def dump(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ... 


def fromfile(filename: str) -> Union[bool, PatchSet]: ...
