# This is a generated file by dfetch. Don't edit this, but edit the manifest.
# For more info see https://dfetch.rtfd.io/en/latest/getting_started.html
dfetch:
  branch: master
  hash: 476a29a874df3840ac2bd916e7097b92
  last_fetch: 14/10/2025, 19:16:12
  patch: ''
  remote_url: https://github.com/paxtonhare/demo-magic.git
  revision: 2a2f439c26a93286dc2adc6ef2a81755af83f36e
  tag: ''
