#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Documentation build configuration file.
"""
# pylint: disable=invalid-name

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

from dfetch import __version__

# -- General configuration ------------------------------------------------

ext_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "_ext"))
sys.path.insert(0, ext_path)

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_sitemap",
    "plantweb.directive",
    "scenario_directive",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxarg.ext",
    "sphinxcontrib_asciinema",
    "sphinxcontrib.details.directive",
    "sphinx-jsonschema",
    "sphinxcontrib.programoutput",
    "sphinx_tabs.tabs",
    "sphinx_autoissues",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Dfetch"
copyright = "2021, Dfetch-org"  # pylint: disable=redefined-builtin
author = "DFetch"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = ""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "venv", "landing-page"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for autosectionlabel extension -------------------------------
autosectionlabel_maxdepth = 3

# Suppress warnings about duplicate labels from argparse directive
suppress_warnings = ["autosectionlabel.manual"]

# Options for sphinx-autoissues
issuetracker = "github"
issuetracker_project = "dfetch-org/dfetch"

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

html_baseurl = "https://dfetch.readthedocs.io/"
sitemap_filename = "sitemap-custom.xml"
sitemap_url_scheme = "{lang}latest/{link}"

html_title = "a source-only no-hassle project-dependency aggregator"
html_favicon = "images/favicon.ico"

html_extra_path = ["robots.txt"]

html_css_files = [
    "css/custom.css",
]

html_logo = "images/dfetch_logo.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "show_powered_by": False,
    "github_user": "dfetch-org",
    "github_repo": "dfetch",
    "github_banner": True,
    "show_related": True,
    "note_bg": "#FFF59C",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["static"]

# html_js_files = [
#     "https://cdn.jsdelivr.net/npm/asciinema-player@3.6.3/dist/bundle/asciinema-player.min.js"
# ]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "about.html",
        "searchbox.html",
        "navigation.html",
        "relations.html",  # needs 'show_related': True theme option to display
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "dfetchdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "dfetch.tex", "Dfetch Documentation", "Dfetch", "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "dfetch", "Dfetch Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "dfetch",
        "Dfetch Documentation",
        author,
        "Dfetch",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Options for asciicasts
sphinxcontrib_asciinema_defaults = {
    "theme": "monokai",
    "preload": True,
    "terminalfontsize": "15px",
    "speed": 1.5,
    "loop": True,
    "autoplay": True,
    "cols": 120,
    "rows": 30,
}
