#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Documentation build configuration file.
"""

# pylint: disable=invalid-name

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from importlib.metadata import PackageNotFoundError, version

# _ext/ must be on sys.path before any local imports.
ext_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "_ext"))
sys.path.insert(0, ext_path)

import dfetch_style  # noqa: E402

dfetch_style.register()

try:
    __version__ = version("dfetch")
except PackageNotFoundError:
    __version__ = "0.0.0"

# Prevent ANSI color codes in command output captured by sphinxcontrib.programoutput.
# Python 3.13+ argparse emits colors when FORCE_COLOR is set; NO_COLOR suppresses
# that regardless of FORCE_COLOR, and dfetch's own Rich console respects it too.
os.environ["NO_COLOR"] = "1"

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_sitemap",
    "sphinx_design",
    "plantweb.directive",
    "scenario_directive",
    "latex_tabs",
    "unique_section_ids",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxarg.ext",
    "sphinxcontrib_asciinema",
    "sphinx-jsonschema",
    "sphinxcontrib.programoutput",
    "sphinx_tabs.tabs",
    "sphinx_autoissues",
    "sphinx_copybutton",
    "colordot",
    "designguide",
]

# Strip shell prompts and Python REPL prompts from copied text
copybutton_prompt_text = r"\$ |>>> |\.\.\. "
copybutton_prompt_is_regexp = True

# scenario_directive: tags that are not group keys (environment markers, etc.)
# The first tag on a feature file that is not in this list determines which
# appendix section the file ends up in.
scenario_non_command_tags = ["remote-svn"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Dfetch"
copyright = "2021, Dfetch-org"  # pylint: disable=redefined-builtin
author = "DFetch"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "venv", "landing-page"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "dfetch"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for autosectionlabel extension -------------------------------
autosectionlabel_maxdepth = 3

# Suppress warnings about duplicate labels from argparse directive
suppress_warnings = [
    "autosectionlabel.reference/commands",
    "autosectionlabel.reference/manifest",
    "autosectionlabel.howto/updating-projects",
]

# Options for sphinx-autoissues
issuetracker = "github"
issuetracker_project = "dfetch-org/dfetch"

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

html_baseurl = "https://dfetch.readthedocs.io/"
sitemap_filename = "sitemap-custom.xml"
sitemap_url_scheme = "{lang}latest/{link}"

html_title = "a source-only no-hassle project-dependency aggregator"
html_favicon = "images/favicon.ico"

html_extra_path = ["robots.txt"]

html_css_files = [
    "fonts/font-awesome/css/fontawesome.min.css",
    "fonts/font-awesome/css/solid.min.css",
    "fonts/font-awesome/css/brands.min.css",
    "css/custom.css",
]

html_js_files = [
    "js/diataxis.js",
]

html_logo = "images/dfetch_logo.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "show_powered_by": False,
    "github_user": "dfetch-org",
    "github_repo": "dfetch",
    "github_banner": True,
    "show_related": True,
    "note_bg": "#FFF59C",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["static"]

# html_js_files = [
#     "https://cdn.jsdelivr.net/npm/asciinema-player@3.6.3/dist/bundle/asciinema-player.min.js"
# ]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "about.html",
        "searchbox.html",
        "navigation.html",
        "relations.html",  # needs 'show_related': True theme option to display
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "dfetchdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_engine = "xelatex"
latex_use_xindy = False

latex_logo = "images/dfetch_logo.png"

_preamble_file = os.path.join(os.path.dirname(__file__), "dfetch_preamble.inc")
with open(_preamble_file, encoding="utf-8") as _f:
    _preamble = _f.read()

latex_elements = {
    "preamble": _preamble,
    # XeLaTeX font setup using vendored fonts (see dfetch.yaml).
    # Both fonts are copied into the LaTeX build root via latex_additional_files,
    # so Path=./ resolves correctly at compile time.
    # \PoiretOne is declared here so it is available to the cover page.
    "fontpkg": r"""
\usepackage{fontspec}
\setsansfont{texgyreheros-regular}[
  Extension=.otf, Path=./, Scale=0.95,
  BoldFont=texgyreheros-bold,
  ItalicFont=texgyreheros-italic,
  BoldItalicFont=texgyreheros-bolditalic]
\renewcommand*\familydefault{\sfdefault}
\setmonofont{JetBrainsMono-Regular}[
  Extension=.ttf, Path=./, Scale=0.85,
  BoldFont=JetBrainsMono-Medium]
\newfontface\PoiretOne{PoiretOne-Regular}[Extension=.ttf, Path=./]
""",
    # Design-token colours for Sphinx's built-in LaTeX style hooks.
    # TitleColor affects TOC entries and any headings not overridden by titlesec.
    # Admonition styling is handled entirely by tcolorbox (see preamble above),
    # so no admonition-specific sphinxsetup keys are needed here.
    "sphinxsetup": (
        "TitleColor={rgb}{0.110,0.098,0.090},"
        "InnerLinkColor={rgb}{0.306,0.498,0.627},"
        "OuterLinkColor={rgb}{0.306,0.498,0.627},"
        "VerbatimColor={rgb}{0.996,0.973,0.941},"
        "VerbatimBorderColor={rgb}{0.906,0.878,0.847},"
        # Table: warm-cream header, white body rows (no striping, matches website)
        "TableRowColorHeader={rgb}{0.996,0.973,0.941},"
        "TableRowColorOdd={rgb}{1.000,1.000,1.000},"
        "TableRowColorEven={rgb}{1.000,1.000,1.000},"
    ),
    # Cover page is in doc/dfetch_cover.inc (listed in latex_additional_files).
    # \makeatletter/\makeatother expose \py@release inside the included file.
    "maketitle": r"\makeatletter\input{dfetch_cover.inc}\makeatother",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        f"dfetch-{__version__}.tex",
        "Dfetch Documentation",
        "Dfetch",
        "manual",
    ),
]

latex_additional_files = [
    "dfetch_cover.inc",
    "static/fonts/poiretone/ttf/PoiretOne-Regular.ttf",
    "static/fonts/texgyreheros/texgyreheros-regular.otf",
    "static/fonts/texgyreheros/texgyreheros-bold.otf",
    "static/fonts/texgyreheros/texgyreheros-italic.otf",
    "static/fonts/texgyreheros/texgyreheros-bolditalic.otf",
    "static/fonts/jetbrains-mono/ttf/JetBrainsMono-Regular.ttf",
    "static/fonts/jetbrains-mono/ttf/JetBrainsMono-Medium.ttf",
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "dfetch", "Dfetch Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "dfetch",
        "Dfetch Documentation",
        author,
        "Dfetch",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Options for asciicasts
sphinxcontrib_asciinema_defaults = {
    "theme": "monokai",
    "preload": True,
    "terminalfontsize": "15px",
    "speed": 1.5,
    "loop": True,
    "autoplay": True,
    "cols": 120,
    "rows": 30,
}
