#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Documentation build configuration file.
"""

# pylint: disable=invalid-name

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("dfetch")
except PackageNotFoundError:
    __version__ = "0.0.0"

# Prevent ANSI color codes in command output captured by sphinxcontrib.programoutput.
# Python 3.13+ argparse emits colors when FORCE_COLOR is set; NO_COLOR suppresses
# that regardless of FORCE_COLOR, and dfetch's own Rich console respects it too.
os.environ["NO_COLOR"] = "1"

# -- General configuration ------------------------------------------------

ext_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "_ext"))
sys.path.insert(0, ext_path)

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_sitemap",
    "sphinx_design",
    "plantweb.directive",
    "scenario_directive",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxarg.ext",
    "sphinxcontrib_asciinema",
    "sphinx-jsonschema",
    "sphinxcontrib.programoutput",
    "sphinx_tabs.tabs",
    "sphinx_autoissues",
    "sphinx_copybutton",
    "colordot",
    "designguide",
]

# Strip shell prompts and Python REPL prompts from copied text
copybutton_prompt_text = r"\$ |>>> |\.\.\. "
copybutton_prompt_is_regexp = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Dfetch"
copyright = "2021, Dfetch-org"  # pylint: disable=redefined-builtin
author = "DFetch"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "venv", "landing-page"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for autosectionlabel extension -------------------------------
autosectionlabel_maxdepth = 3

# Suppress warnings about duplicate labels from argparse directive
suppress_warnings = [
    "autosectionlabel.reference/commands",
    "autosectionlabel.howto/updating-projects",
]

# Options for sphinx-autoissues
issuetracker = "github"
issuetracker_project = "dfetch-org/dfetch"

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

html_baseurl = "https://dfetch.readthedocs.io/"
sitemap_filename = "sitemap-custom.xml"
sitemap_url_scheme = "{lang}latest/{link}"

html_title = "a source-only no-hassle project-dependency aggregator"
html_favicon = "images/favicon.ico"

html_extra_path = ["robots.txt"]

html_css_files = [
    "fonts/font-awesome/css/fontawesome.min.css",
    "fonts/font-awesome/css/solid.min.css",
    "fonts/font-awesome/css/brands.min.css",
    "css/custom.css",
]

html_js_files = [
    "js/diataxis.js",
]

html_logo = "images/dfetch_logo.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "show_powered_by": False,
    "github_user": "dfetch-org",
    "github_repo": "dfetch",
    "github_banner": True,
    "show_related": True,
    "note_bg": "#FFF59C",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["static"]

# html_js_files = [
#     "https://cdn.jsdelivr.net/npm/asciinema-player@3.6.3/dist/bundle/asciinema-player.min.js"
# ]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "about.html",
        "searchbox.html",
        "navigation.html",
        "relations.html",  # needs 'show_related': True theme option to display
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "dfetchdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_logo = "images/dfetch_logo.png"

latex_elements = {
    # Map Unicode check/cross marks used in alternatives.rst to pifont dingbats
    # so pdflatex doesn't abort with "Unicode character not set up for use".
    # Also configure fonts and colours to match the design system.
    "preamble": r"""
\usepackage{newunicodechar}
\usepackage{pifont}
\newunicodechar{✔}{\ding{51}}
\newunicodechar{✘}{\ding{55}}
\usepackage{xcolor}
\definecolor{dfprimary}{HTML}{c2620a}
\definecolor{dfaccent}{HTML}{4e7fa0}
\definecolor{dftextmuted}{HTML}{78716c}
\definecolor{dfnearblack}{HTML}{1c1917}
% Cover page colours (dfetch brand palette)
\definecolor{dfetchCoverTop}{HTML}{3a6682}
\definecolor{dfetchCoverDark}{HTML}{1c1917}
\definecolor{dfetchCoverBottom}{HTML}{c2620a}
\definecolor{dfetchCoverAccent}{HTML}{4e7fa0}
\definecolor{dfetchCoverLight}{HTML}{fef8f0}
% TikZ for cover page
\usepackage{tikz}
""",
    # XeLaTeX font setup: fontspec replaces helvet/fontenc.
    # TeX Gyre Heros is a metrically compatible Helvetica substitute available
    # in every standard TeX Live installation.
    # \PoiretOne is declared here so it is available to the cover page.
    "fontpkg": r"""
\usepackage{fontspec}
\setsansfont{TeX Gyre Heros}[Scale=0.95]
\renewcommand*\familydefault{\sfdefault}
\newfontface\PoiretOne{PoiretOne-Regular}[Extension=.ttf, Path=./]
""",
    # Design-token colours for Sphinx's built-in LaTeX style hooks
    "sphinxsetup": (
        "TitleColor={rgb}{0.761,0.384,0.039},"
        "InnerLinkColor={rgb}{0.306,0.498,0.627},"
        "OuterLinkColor={rgb}{0.306,0.498,0.627},"
        "VerbatimColor={rgb}{0.996,0.973,0.941},"
        "VerbatimBorderColor={rgb}{0.906,0.878,0.847},"
        "noteBorderColor={rgb}{0.306,0.498,0.627},"
        "warningBorderColor={rgb}{0.761,0.384,0.039},"
    ),
    # Cover page is in doc/dfetch_cover.tex (listed in latex_additional_files).
    # \makeatletter/\makeatother expose \py@release inside the included file.
    "maketitle": r"\makeatletter\input{dfetch_cover}\makeatother",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        f"dfetch-{__version__}.tex",
        "Dfetch Documentation",
        "Dfetch",
        "manual",
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "dfetch", "Dfetch Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "dfetch",
        "Dfetch Documentation",
        author,
        "Dfetch",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Options for asciicasts
sphinxcontrib_asciinema_defaults = {
    "theme": "monokai",
    "preload": True,
    "terminalfontsize": "15px",
    "speed": 1.5,
    "loop": True,
    "autoplay": True,
    "cols": 120,
    "rows": 30,
}
