# Schema file (schema.yaml)
manifest:
    version: enum('0.0', 0.0)
    remotes: list(include('remote'), unique_property='name', required=False)
    projects: list(include('project'), unique_property='name, dst')
---
remote:
    name: str()
    url-base: str()
    default: bool(required=False)

project:
    name: str()
    dst: str(required=False)
    branch: str(required=False)
    tag: str(required=False)
    revision: str(required=False)
    url: str(required=False)
    repo-path: str(required=False)
    remote: str(required=False)
    patch: str(required=False)
    vcs: enum('git', 'svn', required=False)
    src: str(required=False)
    ignore: list(str(), required=False)
