name: CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prep-release:
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      security-events: write

  source-provenance:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/source-provenance.yml
    permissions:
      contents: read
      attestations: write
      id-token: write

  build:
    needs: [prep-release, source-provenance]
    if: needs.prep-release.result != 'failure' && needs.source-provenance.result != 'failure'
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
      security-events: write
      attestations: write
      id-token: write
    with:
      release_id: ${{ needs.prep-release.outputs.release_id }}

  run:
    uses: ./.github/workflows/run.yml
    permissions:
      contents: read
      security-events: write

  test:
    needs: source-provenance
    if: always() && (needs.source-provenance.result == 'success' || needs.source-provenance.result == 'skipped')
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      attestations: write
      id-token: write
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  docs:
    needs: prep-release
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: write
    secrets:
      GH_DFETCH_ORG_DEPLOY: ${{ secrets.GH_DFETCH_ORG_DEPLOY }}
    with:
      release_id: ${{ needs.prep-release.outputs.release_id }}
