name: "Docs"

on:
  workflow_call:
    inputs:
      release_id:
        required: false
        type: string
        default: ''
    secrets:
      GH_DFETCH_ORG_DEPLOY:
        required: false

permissions:
  contents: read

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: "Harden the runner (Block egress traffic: Only allow calls to allowed endpoints)"
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: block
        allowed-endpoints: >+
          github.com:443
          pypi.org:443
          files.pythonhosted.org:443
          plantuml.com:80
          plantuml.com:443
          www.plantuml.com:80

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.13'

    - name: Install documentation requirements
      run: |
          pip install .[docs]

    - name: Build docs
      run: "make -C doc html"

  landing-page:
    name: Landing page
    runs-on: ubuntu-latest
    steps:
      - name: "Harden the runner (Block egress traffic: Only allow calls to allowed endpoints)"
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: block
          allowed-endpoints: >+
            github.com:443
            github.com:22
            pypi.org:443
            files.pythonhosted.org:443
            plantuml.com:80
            plantuml.com:443
            www.plantuml.com:80

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install .[docs]

      - name: Build landing-page
        run: "make -C doc/landing-page html"

      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          publish_dir: ./doc/landing-page/_build/html
          external_repository: dfetch-org/dfetch-org.github.io
          publish_branch: main
          deploy_key: ${{ secrets.GH_DFETCH_ORG_DEPLOY }}

  pdf:
    name: PDF Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Harden the runner (Block egress traffic: Only allow calls to allowed endpoints)"
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: block
          allowed-endpoints: >+
            _http._tcp.azure.archive.ubuntu.com:443
            _https._tcp.archive.ubuntu.com:443
            _https._tcp.security.ubuntu.com:443
            archive.ubuntu.com:443
            azure.archive.ubuntu.com:443
            azure.archive.ubuntu.com:80
            files.pythonhosted.org:443
            github.com:443
            api.github.com:443
            uploads.github.com:443
            plantuml.com:443
            plantuml.com:80
            pypi.org:443
            security.ubuntu.com:443
            www.plantuml.com:80

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - name: Install documentation requirements
        run: |
          pip install .[docs]

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended \
            texlive-latex-extra texlive-xetex latexmk

      - name: Build PDF
        run: make -C doc latexpdf

      - name: Store PDF artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dfetch-pdf-documentation
          path: doc/_build/latex/dfetch-*.pdf

      - name: Upload PDF to release
        if: ${{ inputs.release_id }}
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v2.5.0
        with:
          tag_name: ${{ inputs.release_id }}
          files: doc/_build/latex/dfetch-*.pdf
          draft: true
          preserve_order: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
