name: "Docs"

on:
  workflow_call:
    inputs:
      release_id:
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.13'

    - name: Install documentation requirements
      run: |
          pip install .[docs]

    - name: Build docs
      run: "make -C doc html"

  landing-page:
    name: Landing page
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install .[docs]

      - name: Build landing-page
        run: "make -C doc/landing-page html"

      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          publish_dir: ./doc/landing-page/_build/html
          external_repository: dfetch-org/dfetch-org.github.io
          publish_branch: main
          deploy_key: ${{ secrets.GH_DFETCH_ORG_DEPLOY }}

  pdf:
    name: PDF Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - name: Install documentation requirements
        run: |
          pip install .[docs]

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended \
            texlive-latex-extra latexmk

      - name: Build PDF
        run: make -C doc latexpdf

      - name: Store PDF artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dfetch-pdf-documentation
          path: doc/_build/latex/dfetch.pdf

      - name: Upload PDF to release
        if: ${{ inputs.release_id }}
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.5.0
        with:
          tag_name: ${{ inputs.release_id }}
          files: doc/_build/latex/dfetch.pdf
          draft: true
          preserve_order: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
