name: Landing-page

on:
  push:
    branches:
      - main
      - feature/simplify-landing-page

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install .[docs]
          pip install sphinx_design

      - name: Build landing-page
        run: |
          cd doc/landing-page
          make html
      - name: Publish
        uses: tsunematsu21/actions-publish-gh-pages@c04b531c52b8f9d25c596bc6e6a7ddc116b2f3f8 # v1.0.2
        with:
          dir: doc/landing-page/_build/html
          repo: dfetch-org/dfetch-org.github.io
          branch: main
          token: ${{ secrets.GH_DFETCH_ORG_DEPLOY }}
